yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<post_id>/delete/', views.post_delete, name='post_delete'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from core.models import CreatedModel

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(CreatedModel):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        null=True,
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self) -> str:
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Оставьте свой комментарий'
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

    def clean_subject(self):
        data = self.changed_data['text']
        if data == '':
            return forms.ValidationError('Пожалуйста, напишите пост')
        return data


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

    def clean_subject(self):
        data = self.changed_data['text']
        if data == '':
            return forms.ValidationError(
                'Пожалуйста, напишите комментарий')
        return data

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
# from django.views.decorators.cache import cache_page
from .models import Post, Group, Follow
from .forms import PostForm, CommentForm


User = get_user_model()

ITEMS_PER_PAGE = 10


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    paginator = Paginator(post_list, ITEMS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


# @cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, ITEMS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    user_posts = author.posts.all()
    post_count = user_posts.count()
    paginator = Paginator(user_posts, ITEMS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    following = False
    if request.user.is_authenticated:
        if request.user != author.username:
            following = Follow.objects.filter(
                user=request.user, author=author
            ).exists()
    context = {
        'post_count': post_count,
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post_info = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post_info.comments.all()
    context = {
        'post_info': post_info,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        form.save(commit=False).author_id = request.user.pk
        form.save()
        return redirect(
            'posts:profile', username=request.user.username
        )
    return render(request, template, {'form': form, 'is_edit': False})


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post,
    )

    if post.author != request.user:
        return redirect(
            'posts:post_detail', post_id
        )

    if form.is_valid():
        form.save()
        return redirect(
            'posts:post_detail', post_id
        )
    context = {
        'form': form,
        'is_edit': True,
        'post': post,
    }
    return render(request, template, context)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:
        post.delete()
    return redirect('posts:profile', post.author.username)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts, ITEMS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    follow_author = get_object_or_404(User, username=username)
    if follow_author != request.user and (
        not request.user.follower.filter(author=follow_author).exists()
    ):
        Follow.objects.create(
            user=request.user,
            author=follow_author
        )
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    follow_author = get_object_or_404(User, username=username)
    data_follow = request.user.follower.filter(author=follow_author)
    if data_follow.exists():
        data_follow.delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
{% if is_edit %}
  Редактировать запись
{% else %}
  Новая запись
{% endif %}  
{% endblock %} 
  {% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">   
                {% load user_filters %}
                {% if is_edit %}
                Редактировать запись
                {% else %}    
                Новый пост     
                {% endif %}        
              </div>
              <div class="card-body">
                <form method="post" enctype="multipart/form-data"
                      {% if is_edit %}
                      action="{% url 'posts:post_edit' post.pk %}"
                      {% else %}
                      action="{% url 'posts:post_create' %}"
                      {% endif %}
                      >
                  {% csrf_token %}

                  {% for field in form.fields %}
                   {{field.error}}
                  {% endfor %}

                  {% for field in form %}
                  <div class="form-group row my-3 p-3 textarea">
                    <label for="{{ field.id_for_label }}">
                     {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                     {% endif %}
                   </label>    
                    {{ field|addclass:'form-control' }}
                    {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                      </small>
                  {% endif %}
                  </div>
                  {% endfor %}
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}               
                    </button> 
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
  {% endblock %} 

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}Ваши подписки{% endblock %}
{% block content %}
{% load thumbnail %}
  {% block header %}
    <h1>Ваши подписки</h1>
  {% endblock %}
    <article>
      {% include 'posts/includes/switcher.html' %}
      {% if not page_obj %} 
      <h3>Вы ни на кого не подписаны</h3>
      {% endif %} 
      {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}      
      <p>{{ post.text }}</p>
      {% if post.group %}   
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %} 
      {% endif %} 
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
      {% include 'posts/includes/paginator.html' %}
    </article>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %} 

{% block content %}
{% load thumbnail %}
  {% block header %}
  <h1>{{ group.title }} </h1>
  {% endblock %}
  <p>
    {{ group.description }}
  </p>
  <article>
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}      
    <p>{{ post.text }}</p>
    {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load thumbnail %}
  {% block header %}
    <h1>Последние обновления на сайте</h1>
  {% endblock %}
    <article>
      {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
          <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}      
      <p>{{ post.text }}</p>
      {% if post.group %}   
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %} 
      {% endif %} 
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
      {% include 'posts/includes/paginator.html' %}
    </article>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост {{ post_info.text|truncatechars:30 }} {% endblock %}
{% block content %}
{% load thumbnail %}
{% load user_filters %}
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post_info.pub_date|date:"d E Y" }}
            </li>
            {% if post.group %}  
            <li class="list-group-item">
              Группа: {{post.group.title}}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            </li>
            {% endif %}  
            <li class="list-group-item">
              Автор: {{ post_info.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span > {{ post_info.author.posts.count }} </span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post_info.author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post_info.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post_info.text }}
          </p>
          {% if request.user.id == post_info.author.id %}
          <a class="btn btn-primary" href={% url 'posts:post_edit' post_info.pk %}>
            редактировать запись
          </a>
          <a class="btn btn-danger" href={% url 'posts:post_delete' post_info.pk %}>
            удалить запись
          </a>
          {% endif %}
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post_info.id %}">
                  {% csrf_token %}      
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% endif %}

          {% for comment in comments %}
            <div class="media mb-4">
              <div class="media-body">
                <h5 class="mt-0">
                  <a href="{% url 'posts:profile' comment.author.username %}">
                    {{ comment.author.username }}
                  </a>
                </h5>
                <p>
                  {{ comment.text }}
                </p>
                <i>
                  {{ comment.pub_date|date:"d E Y" }}, {{ comment.pub_date|time:"H:i" }}
                </i>
              </div>
            </div>
          {% endfor %} 
        </article>
      </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author.get_full_name }} {% endblock %}
{% block content %}
{% load thumbnail %}
      <div class="mb-5">        
        <h1>Все посты пользователя {{ author.get_full_name }} </h1>
        <h3>Всего постов: {{ post_count }} </h3>   
        {% if request.user != author %}
          {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
              Отписаться
            </a>
          {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
          {% endif %}
        {% endif %}
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </article>      
        {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>      
        {% endif %}    
        <hr>   
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        {% include 'posts/includes/paginator.html' %}
      </div>
{% endblock %}